package com.xjd2.sthjsystem.dataview;

import java.util.Date;
import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.util.BeanContainer;
import com.vaadin.data.util.BeanItem;
import com.vaadin.server.Sizeable;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.VerticalSplitPanel;
import com.xjd2.sthjsystem.instance.CommonProduct;
import com.xjd2.sthjsystem.instance.CommonProduct.ProductStatus;
import com.xjd2.sthjsystem.instance.ThematicOrder;

public class CommonDataTableComposite extends CustomComponent
{

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private VerticalLayout mainLayout;
    @AutoGenerated
    private VerticalSplitPanel verticalSplitPanel_1;
//    @AutoGenerated
//    private Table commonInfoTable;
    @AutoGenerated
    private Table commonDataTable;
    private Panel abovePanel;
    private Panel belowPanel;
    private CommonDataTableViewInter presenter;
    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public CommonDataTableComposite()
    {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private VerticalLayout buildMainLayout()
    {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // verticalSplitPanel_1
        verticalSplitPanel_1 = buildVerticalSplitPanel_1();
        verticalSplitPanel_1.setSplitPosition(70, Sizeable.UNITS_PERCENTAGE);
        mainLayout.addComponent(verticalSplitPanel_1);
        mainLayout.setExpandRatio(verticalSplitPanel_1, 1.0f);
        
        return mainLayout;
    }

    @AutoGenerated
    private VerticalSplitPanel buildVerticalSplitPanel_1()
    {
        // common part: create layout
        verticalSplitPanel_1 = new VerticalSplitPanel();
        verticalSplitPanel_1.setImmediate(false);
        verticalSplitPanel_1.setWidth("100.0%");
        verticalSplitPanel_1.setHeight("100.0%");
        
        abovePanel = new Panel("共性产品数据信息");
        abovePanel.setImmediate(false);
        abovePanel.setWidth("100.0%");
        abovePanel.setHeight("100.0%");
        verticalSplitPanel_1.addComponent(abovePanel);
        
        // themticOrderTable
        commonDataTable = new Table("共性产品数据信息");
        commonDataTable.setImmediate(false);
        commonDataTable.setWidth("100.0%");
        commonDataTable.setHeight("100.0%");
        abovePanel.setContent(commonDataTable);
        generateThematicDataTabel();
        
        belowPanel = new Panel("数据预览");
        belowPanel.setImmediate(false);
        belowPanel.setWidth("100.0%");
        belowPanel.setHeight("100.0%");
        verticalSplitPanel_1.addComponent(belowPanel);
        
//        
        return verticalSplitPanel_1;
    }
    
    private void generateThematicDataTabel()
    {
        commonDataTable.setCaption("共性产品数据情况");
        commonDataTable.setSelectable(true);
        commonDataTable.setImmediate(true);
        commonDataTable.addContainerProperty("id",String.class,  null);
        commonDataTable.addContainerProperty("name",String.class,  null);
//        commonDataTable.addContainerProperty("taskId",String.class,  null);
        commonDataTable.addContainerProperty("produceDate",Date.class,  null);
        commonDataTable.addContainerProperty("coverRange",String.class,  null);
        commonDataTable.addContainerProperty("spaceResolution",String.class,  null);
        commonDataTable.addContainerProperty("timeResolution",String.class,  null);
        commonDataTable.addContainerProperty("temporal",String.class,  null);
        commonDataTable.addContainerProperty("operation",OptionGroup.class,  null);
        
        commonDataTable.setColumnHeader("id", "ID");
        commonDataTable.setColumnHeader("name", "数据名称");
//        commonDataTable.setColumnHeader("taskId", "关联订单ID");
        commonDataTable.setColumnHeader("produceDate", "生产日期");
        commonDataTable.setColumnHeader("coverRange", "覆盖范围");
        commonDataTable.setColumnHeader("spaceResolution", "空间分辨率");
        commonDataTable.setColumnHeader("timeResolution", "时间分辨率");
        commonDataTable.setColumnHeader("temporal", "时相");
        commonDataTable.setColumnHeader("operation", "操作");
        
        commonDataTable.addValueChangeListener(new Property.ValueChangeListener() {
            public void valueChange(ValueChangeEvent event) {
                presenter.displayData();
//                ((String)themticOrderTable.getItem(themticOrderTable.getValue()).getItemProperty("productName").getValue());
            }
        });
        
    }
    
    
    public void setPresenter(CommonDataTableViewInter listener)
    {
       this.presenter = listener;
    }
    
    public void setCommonDataTabelContent(List<ThematicOrder> orders)
    {
        commonDataTable.removeAllItems(); 
//        BeanContainer<String,ThematicOrder> beanC = new BeanContainer<String,ThematicOrder>(ThematicOrder.class);
//        beanC.setBeanIdProperty("taskId");
//        ComboBox operationComboBox;
        OptionGroup group;
        for(ThematicOrder order:orders)
        {
//            beanC.addBean(order);
            group = new OptionGroup();
            group.addItem("接受生产");
            group.addItem("拒绝生产");
            group.setImmediate(true);
            commonDataTable.addItem(new Object[] {order.getTaskId(),order.getSource(),order.getName(),
                    order.getProductName(),order.getOrderDate(),order.getRange(),order.getRangeScale(),order.getStatus(),group}, order.getTaskId());
            
        }
    }
    
    /**
     * 显示预览图片
     */
    public void displayImage()
    {
//        commonInfoTable.removeAllItems();
//        Button operateButton;
//        for(CommonProduct need:needs)
//        {
////            beanC.addBean(order);
//            operateButton = new Button("订购");
//            commonInfoTable.addItem(new Object[] {need.getName(),need.getStartDate(),need.getEndDate(),need.getCoverRange(),need.getTimeResolution(),
//                    need.getSpaceResolution()," ",need.getNpStatus(),operateButton},need.getName());
//            
//        }
    }


}
