package com.xjd2.sthjsystem;

import java.util.Date;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Panel;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class CommonOrderTableComposite extends CustomComponent
{

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private VerticalLayout mainLayout;
    @AutoGenerated
    private Panel abovePanel;
    @AutoGenerated
    private VerticalLayout verticalLayout_2;
    @AutoGenerated
    private Table commonOrderTable;
    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public CommonOrderTableComposite()
    {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private VerticalLayout buildMainLayout()
    {
        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);
        
        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");
        
        // abovePanel
        abovePanel = buildAbovePanel();
        mainLayout.addComponent(abovePanel);
        mainLayout.setExpandRatio(abovePanel, 1.0f);
        
        return mainLayout;
    }

    @AutoGenerated
    private Panel buildAbovePanel()
    {
        // common part: create layout
        abovePanel = new Panel("共性产品订单情况");
        abovePanel.setImmediate(false);
        abovePanel.setWidth("100.0%");
        abovePanel.setHeight("100.0%");
        
        // verticalLayout_2
        verticalLayout_2 = buildVerticalLayout_2();
        abovePanel.setContent(verticalLayout_2);
        
        return abovePanel;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_2()
    {
        // common part: create layout
        verticalLayout_2 = new VerticalLayout();
        verticalLayout_2.setImmediate(false);
        verticalLayout_2.setWidth("100.0%");
        verticalLayout_2.setHeight("100.0%");
        verticalLayout_2.setMargin(false);
        
        // commonOrderTable
        commonOrderTable = new Table();
        commonOrderTable.setImmediate(false);
        commonOrderTable.setWidth("100.0%");
        commonOrderTable.setHeight("100.0%");
        verticalLayout_2.addComponent(commonOrderTable);
        verticalLayout_2.setExpandRatio(commonOrderTable, 1.0f);
        generateCommonOrderTable();
        
        
        return verticalLayout_2;
    }
    
    private void generateCommonOrderTable()
    {
//        commonOrderTable.setCaption("共性产品订单情况");
        commonOrderTable.addContainerProperty("订单ID",Integer.class,  null);
//        commonOrderTable.addContainerProperty("订单来源",String.class,  null);
        commonOrderTable.addContainerProperty("订单名称",String.class,  null);
        commonOrderTable.addContainerProperty("订单时间",Date.class,  null);
        commonOrderTable.addContainerProperty("空间覆盖范围",String.class,  null);
        commonOrderTable.addContainerProperty("区域",String.class,  null);
        commonOrderTable.addContainerProperty("是否接受生产",Boolean.class,  null);
        commonOrderTable.addContainerProperty("生产状态",String.class,  null);
        commonOrderTable.addContainerProperty("操作",String.class,  null);
    }

}
