package com.xjd2.sthjsystem;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.Sizeable;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.Accordion;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;
import com.xjd2.sthjsystem.dataview.DataComposite;
import com.xjd2.sthjsystem.orderview.OrdersComposite;

public class SthjComposite extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private HorizontalLayout bottomLayout;
	@AutoGenerated
	private HorizontalLayout middleLayout;
	@AutoGenerated
	private HorizontalSplitPanel midSplitPanel;
	@AutoGenerated
	private TabSheet midTab;
	@AutoGenerated
	private Accordion leftAccordion;
	@AutoGenerated
	private HorizontalLayout topLayout;
	@AutoGenerated
	private Embedded systemLogo;
	
	private Panel leftPanel;
	private Panel rightPanel;
	private OrdersComposite orderComposite;
	private DataComposite dataComposite;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public SthjComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		mainLayout.addComponent(verticalLayout_2);
		mainLayout.setComponentAlignment(verticalLayout_2, new Alignment(48));
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("1200px");
		verticalLayout_2.setHeight("850px");
//		verticalLayout_2.setSizeFull();
		verticalLayout_2.setMargin(false);
		
		// topLayout
		topLayout = buildTopLayout();
		verticalLayout_2.addComponent(topLayout);
//		verticalLayout_2.setExpandRatio(topLayout, 1.0f);
		
		// middleLayout
		middleLayout = buildMiddleLayout();
//		middleLayout.setSizeFull();
		verticalLayout_2.addComponent(middleLayout);
		verticalLayout_2.setExpandRatio(middleLayout, 1.0f);
		
		// bottomLayout
		bottomLayout = new HorizontalLayout();
		bottomLayout.setImmediate(false);
		bottomLayout.setWidth("1200px");
		bottomLayout.setHeight("50px");
		bottomLayout.setMargin(false);
		verticalLayout_2.addComponent(bottomLayout);
//		verticalLayout_2.setExpandRatio(bottomLayout, 1.0f);
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildTopLayout() {
		// common part: create layout
		topLayout = new HorizontalLayout();
		topLayout.setImmediate(false);
		topLayout.setWidth("1200px");
		topLayout.setHeight("85px");
		topLayout.setMargin(false);
		
		// systemLogo
		systemLogo = new Embedded();
		systemLogo.setImmediate(false);
		systemLogo.setWidth("100.0%");
		systemLogo.setHeight("-1px");
		systemLogo.setSource(new ThemeResource("imgs/banner.png"));
		systemLogo.setType(1);
		systemLogo.setMimeType("image/png");
		topLayout.addComponent(systemLogo);
		
		return topLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildMiddleLayout() {
		// common part: create layout
		middleLayout = new HorizontalLayout();
		middleLayout.setImmediate(false);
		middleLayout.setWidth("1200px");
		middleLayout.setHeight("100%");
		middleLayout.setMargin(false);
		
		addFunctionPanels();
//		middleLayout.addComponent(orderComposite);	
		// midSplitPanel
//		midTab = buildMidSplitPanel();
//		middleLayout.addComponent(midTab);
		
		return middleLayout;
	}

	private void addFunctionPanels()
	{
		midTab = new TabSheet();
		midTab.setImmediate(false);
		midTab.setWidth("100%");
		midTab.setHeight("100%");
		middleLayout.addComponent(midTab);
		
		orderComposite = new OrdersComposite();
		orderComposite.setWidth("1200px");
		orderComposite.setHeight("100%");
		
		midTab.addTab(orderComposite).setCaption("订单管理");
		
		//TODO: 其他功能面板
		dataComposite = new  DataComposite();
		dataComposite.setWidth("1200px");
		dataComposite.setHeight("100%");
		
//		HorizontalLayout tab2 = new HorizontalLayout();
		midTab.addTab(dataComposite).setCaption("数据管理");
		
		HorizontalLayout tab3 = new HorizontalLayout();
		midTab.addTab(tab3).setCaption("生产任务管理");
		
		HorizontalLayout tab4 = new HorizontalLayout();
		midTab.addTab(tab4).setCaption("生态环境格局遥感监测专题产品");
		
		HorizontalLayout tab5 = new HorizontalLayout();
		midTab.addTab(tab5).setCaption("生态环境功能遥感监测专题产品");
		
		HorizontalLayout tab6 = new HorizontalLayout();
		midTab.addTab(tab6).setCaption("生态环境问题遥感监测专题产品");
		
		HorizontalLayout tab7 = new HorizontalLayout();
		midTab.addTab(tab7).setCaption("生态环境遥感诊断");
		
		HorizontalLayout tab8 = new HorizontalLayout();
		midTab.addTab(tab8).setCaption("系统管理");
	}

}
